package eds.database;

import eds.database.Records.StatisticsAndMetricsRecord;
import eds.database.Records.TradeRecord;
import eds.framework.Trace;
import eds.model.StatisticsCollector;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Queries — Implementation of IQueries.
 *
 * Responsibilities:
 * - Persist simulation run records (statistics_and_metrics table)
 * - Persist trade records linked to a run (trades table)
 * - Retrieve run records and trades for the results view
 *
 * All database access goes through Database.getInstance().getConnection().
 *
 * Integration:
 * - StatisticsCollector.Snapshot -> buildRecord() -> save() -> DB
 * - findById(runId) -> StatisticsAndMetricsRecord -> PerformanceDescriber
 */
public class Queries implements IQueries {

    // ── Snapshot - Record conversion ──────────────────────────────────────────

    /**
     * Converts a StatisticsCollector.Snapshot and engine config parameters
     * into a StatisticsAndMetricsRecord ready for persistence.
     *
     * This is the single mapping point between the model layer and database layer.
     * Called by Controller after simulation completes.
     */
    public StatisticsAndMetricsRecord buildRecord(
            StatisticsCollector.Snapshot snap,
            String runName,
            long seed,
            double meanValidation,
            double meanMarket,
            double meanLimit,
            double meanExecution,
            double meanArrival,
            double simulationTime) {

        // unpack service point lists by known index order:
        // 0=validation, 1=market matching, 2=limit matching, 3=execution
        List<Double> util = snap.servicePointUtilization();
        List<Double> queue = snap.averageQueueLengthPerServicePoint();

        return new StatisticsAndMetricsRecord(
                0, // id — generated by DB
                LocalDateTime.now().toString(), // runTimestamp
                runName,
                seed,
                meanValidation,
                meanMarket,
                meanLimit,
                meanExecution,
                meanArrival,
                simulationTime,
                (int) snap.totalArrivedOrders(), // totalOrders
                (int) snap.totalTrades(), // totalTrades
                (int) snap.totalExecutedOrders(), // filledOrders
                (int) (snap.totalArrivedOrders() // cancelledOrders — derived
                        - snap.totalExecutedOrders()
                        - snap.remainingOrdersInBook()),
                snap.remainingOrdersInBook(), // remainingOrders
                snap.vwap(),
                snap.averageMidPrice(),
                snap.minPrice(),
                snap.maxPrice(),
                snap.averageSpread(),
                snap.averageWaitingTime(), // avgLatency
                snap.throughput(),
                snap.fillRate(), // decimal 0.0–1.0
                safeGet(util, 0), // utilizationValidation
                safeGet(util, 1), // utilizationMarket
                safeGet(util, 2), // utilizationLimit
                safeGet(util, 3), // utilizationExecution
                safeGet(queue, 0), // avgQueueValidation
                safeGet(queue, 1), // avgQueueMarket
                safeGet(queue, 2), // avgQueueLimit
                safeGet(queue, 3) // avgQueueExecution
        );
    }

    // ── Save run ──────────────────────────────────────────────────────────────

    /**
     * Persists a completed simulation run to statistics_and_metrics table.
     *
     * @param record fully populated record (id field ignored — generated by DB)
     * @return the generated run id, or -1 if insert failed
     */
    @Override
    public int saveStatisticsAndMetrics(StatisticsAndMetricsRecord record) {
        String sql = """
                INSERT INTO statistics_and_metrics (
                    run_timestamp, run_name,
                    seed, mean_validation, mean_market, mean_limit,
                    mean_execution, mean_arrival, simulation_time,
                    total_orders, total_trades, filled_orders,
                    cancelled_orders, remaining_orders,
                    vwap, avg_mid_price, min_price, max_price,
                    avg_spread, avg_latency, throughput, fill_rate,
                    utilization_validation, utilization_market,
                    utilization_limit, utilization_execution,
                    avg_queue_validation, avg_queue_market,
                    avg_queue_limit, avg_queue_execution
                ) VALUES (
                    ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
                )
                """;

        try (PreparedStatement stmt = Database.getInstance()
                .getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, record.runTimestamp());
            stmt.setString(2, record.runName());
            stmt.setLong(3, record.seed());
            stmt.setDouble(4, record.meanValidation());
            stmt.setDouble(5, record.meanMarket());
            stmt.setDouble(6, record.meanLimit());
            stmt.setDouble(7, record.meanExecution());
            stmt.setDouble(8, record.meanArrival());
            stmt.setDouble(9, record.simulationTime());
            stmt.setInt(10, record.totalOrders());
            stmt.setInt(11, record.totalTrades());
            stmt.setInt(12, record.filledOrders());
            stmt.setInt(13, record.cancelledOrders());
            stmt.setInt(14, record.remainingOrders());
            stmt.setDouble(15, record.vwap());
            stmt.setDouble(16, record.avgMidPrice());
            stmt.setDouble(17, record.minPrice());
            stmt.setDouble(18, record.maxPrice());
            stmt.setDouble(19, record.avgSpread());
            stmt.setDouble(20, record.avgLatency());
            stmt.setDouble(21, record.throughput());
            stmt.setDouble(22, record.fillRate());
            stmt.setDouble(23, record.utilizationValidation());
            stmt.setDouble(24, record.utilizationMarket());
            stmt.setDouble(25, record.utilizationLimit());
            stmt.setDouble(26, record.utilizationExecution());
            stmt.setDouble(27, record.avgQueueValidation());
            stmt.setDouble(28, record.avgQueueMarket());
            stmt.setDouble(29, record.avgQueueLimit());
            stmt.setDouble(30, record.avgQueueExecution());

            stmt.executeUpdate();

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    int runId = keys.getInt(1);
                    Trace.out(Trace.Level.INFO, "Queries: saved run id=" + runId);
                    return runId;
                }
            }

        } catch (SQLException e) {
            Trace.out(Trace.Level.ERR, "Queries: save failed — " + e.getMessage());
        }

        return -1;
    }

    // ── Save all trades ───────────────────────────────────────────────────────

    /**
     * Persists all trades in a single transaction linked to runId.
     * Rolls back entirely on failure — no partial saves.
     *
     * @return number of trades saved, or -1 if transaction failed
     */
    @Override
    public int saveAllTrades(List<TradeRecord> trades, int runId) {
        return -1;
    }

    // ── Find all ──────────────────────────────────────────────────────────────

    /**
     * Returns all simulation runs, most recent first.
     * Returns empty list if none found.
     */
    @Override
    public List<StatisticsAndMetricsRecord> findAll() {
        List<StatisticsAndMetricsRecord> results = new ArrayList<>();

        return results;
    }

    // ── Find by id ────────────────────────────────────────────────────────────

    /**
     * Returns a single run by id.
     * Returns Optional.empty() if not found — callers must handle absence.
     *
     * Used by ResultsView to load the just-completed run:
     * queries.findById(runId).ifPresent(record -> describer = new
     * PerformanceDescriber(record))
     */
    @Override
    public Optional<StatisticsAndMetricsRecord> findById(int id) {
        return Optional.empty();
    }

    // ── Find trades by run id ─────────────────────────────────────────────────

    /**
     * Returns all trades for a run ordered by conclusion time.
     * Returns empty list if none found.
     */
    @Override
    public List<TradeRecord> findTradesByRunId(int runId) {
        List<TradeRecord> results = new ArrayList<>();

        return results;
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Maps a ResultSet row to StatisticsAndMetricsRecord.
     * Single source of truth for column-to-field mapping.
     * Used by findAll() and findById().
     */
    private StatisticsAndMetricsRecord mapRecord(ResultSet rs) throws SQLException {
        return new StatisticsAndMetricsRecord();
    }

    /**
     * Safe list access — returns 0.0 if index is out of bounds.
     * Prevents IndexOutOfBoundsException if servicePointCount was wrong.
     */
    private double safeGet(List<Double> list, int index) {
        return (list != null && index < list.size()) ? list.get(index) : 0.0;
    }
}