package eds.database;

import eds.database.Records.StatisticsAndMetricsRecord;
import eds.database.Records.TradeRecord;
import eds.framework.Trace;
import eds.model.StatisticsCollector;

import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Queries — Implementation of IQueries.
 *
 * Responsibilities:
 * - Persist simulation run records (statistics_and_metrics table)
 * - Persist trade records linked to a run (trades table)
 * - Retrieve run records and trades for the results view
 *
 * All database access goes through Database.getInstance().getConnection().
 *
 * Integration:
 * - StatisticsCollector.Snapshot -> buildRecord() -> save() -> DB
 * - findById(runId) -> StatisticsAndMetricsRecord -> PerformanceDescriber
 */
public class Queries implements IQueries {

    // ── Snapshot - Record conversion ──────────────────────────────────────────

    /**
     * Converts a StatisticsCollector.Snapshot and engine config parameters
     * into a StatisticsAndMetricsRecord ready for persistence.
     *
     * This is the single mapping point between the model layer and database layer.
     * Called by Controller after simulation completes.
     */
    public StatisticsAndMetricsRecord buildRecord(
            StatisticsCollector.Snapshot snap,
            String runName,
            long seed,
            double meanValidation,
            double meanMarket,
            double meanLimit,
            double meanExecution,
            double meanArrival,
            double simulationTime) {

        // unpack service point lists by known index order:
        // 0=validation, 1=market matching, 2=limit matching, 3=execution
        List<Double> util = snap.servicePointUtilization();
        List<Double> queue = snap.averageQueueLengthPerServicePoint();

        return new StatisticsAndMetricsRecord(
                0, // id — generated by DB
                LocalDateTime.now().toString(), // runTimestamp
                runName,
                seed,
                meanValidation,
                meanMarket,
                meanLimit,
                meanExecution,
                meanArrival,
                simulationTime,
                (int) snap.totalArrivedOrders(), // totalOrders
                (int) snap.totalTrades(), // totalTrades
                (int) snap.totalExecutedOrders(), // filledOrders
                (int) (snap.totalArrivedOrders() // cancelledOrders — derived
                        - snap.totalExecutedOrders()
                        - snap.remainingOrdersInBook()),
                snap.remainingOrdersInBook(), // remainingOrders
                snap.vwap(),
                snap.averageMidPrice(),
                snap.minPrice(),
                snap.maxPrice(),
                snap.averageSpread(),
                snap.averageWaitingTime(), // avgLatency
                snap.throughput(),
                snap.fillRate(), // decimal 0.0–1.0
                safeGet(util, 0), // utilizationValidation
                safeGet(util, 1), // utilizationMarket
                safeGet(util, 2), // utilizationLimit
                safeGet(util, 3), // utilizationExecution
                safeGet(queue, 0), // avgQueueValidation
                safeGet(queue, 1), // avgQueueMarket
                safeGet(queue, 2), // avgQueueLimit
                safeGet(queue, 3) // avgQueueExecution
        );
    }

    // ── Save run ──────────────────────────────────────────────────────────────

    /**
     * Persists a completed simulation run to statistics_and_metrics table.
     *
     * @param record fully populated record (id field ignored — generated by DB)
     * @return the generated run id, or -1 if insert failed
     */
    @Override
    public int saveStatisticsAndMetrics(StatisticsAndMetricsRecord record) {
        String sql = """
                INSERT INTO statistics_and_metrics (
                    run_timestamp, run_name,
                    seed, mean_validation, mean_market, mean_limit,
                    mean_execution, mean_arrival, simulation_time,
                    total_orders, total_trades, filled_orders,
                    cancelled_orders, remaining_orders,
                    vwap, avg_mid_price, min_price, max_price,
                    avg_spread, avg_latency, throughput, fill_rate,
                    utilization_validation, utilization_market,
                    utilization_limit, utilization_execution,
                    avg_queue_validation, avg_queue_market,
                    avg_queue_limit, avg_queue_execution
                ) VALUES (
                    ?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?
                )
                """;

        try (PreparedStatement stmt = Database.getInstance()
                .getConnection().prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            stmt.setString(1, record.runTimestamp());
            stmt.setString(2, record.runName());
            stmt.setLong(3, record.seed());
            stmt.setDouble(4, record.meanValidation());
            stmt.setDouble(5, record.meanMarket());
            stmt.setDouble(6, record.meanLimit());
            stmt.setDouble(7, record.meanExecution());
            stmt.setDouble(8, record.meanArrival());
            stmt.setDouble(9, record.simulationTime());
            stmt.setInt(10, record.totalOrders());
            stmt.setInt(11, record.totalTrades());
            stmt.setInt(12, record.filledOrders());
            stmt.setInt(13, record.cancelledOrders());
            stmt.setInt(14, record.remainingOrders());
            stmt.setDouble(15, record.vwap());
            stmt.setDouble(16, record.avgMidPrice());
            stmt.setDouble(17, record.minPrice());
            stmt.setDouble(18, record.maxPrice());
            stmt.setDouble(19, record.avgSpread());
            stmt.setDouble(20, record.avgLatency());
            stmt.setDouble(21, record.throughput());
            stmt.setDouble(22, record.fillRate());
            stmt.setDouble(23, record.utilizationValidation());
            stmt.setDouble(24, record.utilizationMarket());
            stmt.setDouble(25, record.utilizationLimit());
            stmt.setDouble(26, record.utilizationExecution());
            stmt.setDouble(27, record.avgQueueValidation());
            stmt.setDouble(28, record.avgQueueMarket());
            stmt.setDouble(29, record.avgQueueLimit());
            stmt.setDouble(30, record.avgQueueExecution());

            stmt.executeUpdate();

            try (ResultSet keys = stmt.getGeneratedKeys()) {
                if (keys.next()) {
                    int runId = keys.getInt(1);
                    Trace.out(Trace.Level.INFO, "Queries: saved run id=" + runId);
                    return runId;
                }
            }

        } catch (SQLException e) {
            Trace.out(Trace.Level.ERR, "Queries: save failed — " + e.getMessage());
        }

        return -1;
    }

    // ── Save all trades ───────────────────────────────────────────────────────

    /**
     * Persists all trades in a single transaction linked to runId.
     * Rolls back entirely on failure — no partial saves.
     *
     * @return number of trades saved, or -1 if transaction failed
     */
    @Override
    public int saveAllTrades(List<TradeRecord> trades, int runId) {
        if (trades == null || trades.isEmpty()) {
            Trace.out(Trace.Level.INFO, "Queries: no trades to save for run id=" + runId);
            return 0;
        }

        String sql = """
                INSERT INTO trades (id, run_id, buy_order_id, sell_order_id, price, share_size, conclusion_time)
                VALUES (?, ?, ?, ?, ?, ?, ?)
                """;

        Connection conn = Database.getInstance().getConnection();

        try {
            conn.setAutoCommit(false);

            try (PreparedStatement stmt = conn.prepareStatement(sql)) {
                for (TradeRecord trade : trades) {
                    stmt.setString(1, trade.id());
                    stmt.setInt(2, runId);
                    stmt.setString(3, trade.buyOrderId());
                    stmt.setString(4, trade.sellOrderId());
                    stmt.setDouble(5, trade.price());
                    stmt.setInt(6, trade.shareSize());
                    stmt.setDouble(7, trade.conclusionTime());
                    stmt.addBatch();
                }

                int[] results = stmt.executeBatch();
                conn.commit();

                Trace.out(Trace.Level.INFO, "Queries: saved " + results.length
                        + " trades for run id=" + runId);
                return results.length;

            } catch (SQLException e) {
                conn.rollback();
                Trace.out(Trace.Level.ERR, "Queries: saveAll rolled back — " + e.getMessage());
                return -1;
            } finally {
                conn.setAutoCommit(true); // always restore — prevents connection leak
            }

        } catch (SQLException e) {
            Trace.out(Trace.Level.ERR, "Queries: saveAll transaction setup failed — " + e.getMessage());
            return -1;
        }
    }

    // ── Find all ──────────────────────────────────────────────────────────────

    /**
     * Returns all simulation runs, most recent first.
     * Returns empty list if none found.
     */
    @Override
    public List<StatisticsAndMetricsRecord> findAll() {
        String sql = "SELECT * FROM statistics_and_metrics ORDER BY id DESC";
        List<StatisticsAndMetricsRecord> results = new ArrayList<>();

        try (PreparedStatement stmt = Database.getInstance()
                .getConnection().prepareStatement(sql);
                ResultSet rs = stmt.executeQuery()) {

            while (rs.next()) {
                results.add(mapRecord(rs));
            }

            Trace.out(Trace.Level.INFO, "Queries: findAll returned " + results.size() + " runs");

        } catch (SQLException e) {
            Trace.out(Trace.Level.ERR, "Queries: findAll failed — " + e.getMessage());
        }

        return results;
    }

    // ── Find by id ────────────────────────────────────────────────────────────

    /**
     * Returns a single run by id.
     * Returns Optional.empty() if not found — callers must handle absence.
     *
     * Used by ResultsView to load the just-completed run:
     * queries.findById(runId).ifPresent(record -> describer = new
     * PerformanceDescriber(record))
     */
    @Override
    public Optional<StatisticsAndMetricsRecord> findById(int id) {
        String sql = "SELECT * FROM statistics_and_metrics WHERE id = ?";

        try (PreparedStatement stmt = Database.getInstance()
                .getConnection().prepareStatement(sql)) {

            stmt.setInt(1, id);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    Trace.out(Trace.Level.INFO, "Queries: findById found id=" + id);
                    return Optional.of(mapRecord(rs));
                }
            }

        } catch (SQLException e) {
            Trace.out(Trace.Level.ERR, "Queries: findById failed id=" + id
                    + " — " + e.getMessage());
        }

        Trace.out(Trace.Level.WAR, "Queries: findById — no record for id=" + id);
        return Optional.empty();
    }

    // ── Find trades by run id ─────────────────────────────────────────────────

    /**
     * Returns all trades for a run ordered by conclusion time.
     * Returns empty list if none found.
     */
    @Override
    public List<TradeRecord> findTradesByRunId(int runId) {
        String sql = "SELECT * FROM trades WHERE run_id = ? ORDER BY conclusion_time ASC";
        List<TradeRecord> results = new ArrayList<>();

        try (PreparedStatement stmt = Database.getInstance()
                .getConnection().prepareStatement(sql)) {

            stmt.setInt(1, runId);

            try (ResultSet rs = stmt.executeQuery()) {
                while (rs.next()) {
                    results.add(new TradeRecord(
                            rs.getString("id"),
                            rs.getInt("run_id"),
                            rs.getString("buy_order_id"),
                            rs.getString("sell_order_id"),
                            rs.getDouble("price"),
                            rs.getInt("share_size"),
                            rs.getDouble("conclusion_time")));
                }
            }

            Trace.out(Trace.Level.INFO, "Queries: findTradesByRunId returned "
                    + results.size() + " trades for run id=" + runId);

        } catch (SQLException e) {
            Trace.out(Trace.Level.ERR, "Queries: findTradesByRunId failed run_id="
                    + runId + " — " + e.getMessage());
        }

        return results;
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    /**
     * Maps a ResultSet row to StatisticsAndMetricsRecord.
     * Single source of truth for column-to-field mapping.
     * Used by findAll() and findById().
     */
    private StatisticsAndMetricsRecord mapRecord(ResultSet rs) throws SQLException {
        return new StatisticsAndMetricsRecord(
                rs.getInt("id"),
                rs.getString("run_timestamp"),
                rs.getString("run_name"),
                rs.getLong("seed"),
                rs.getDouble("mean_validation"),
                rs.getDouble("mean_market"),
                rs.getDouble("mean_limit"),
                rs.getDouble("mean_execution"),
                rs.getDouble("mean_arrival"),
                rs.getDouble("simulation_time"),
                rs.getInt("total_orders"),
                rs.getInt("total_trades"),
                rs.getInt("filled_orders"),
                rs.getInt("cancelled_orders"),
                rs.getInt("remaining_orders"),
                rs.getDouble("vwap"),
                rs.getDouble("avg_mid_price"),
                rs.getDouble("min_price"),
                rs.getDouble("max_price"),
                rs.getDouble("avg_spread"),
                rs.getDouble("avg_latency"),
                rs.getDouble("throughput"),
                rs.getDouble("fill_rate"),
                rs.getDouble("utilization_validation"),
                rs.getDouble("utilization_market"),
                rs.getDouble("utilization_limit"),
                rs.getDouble("utilization_execution"),
                rs.getDouble("avg_queue_validation"),
                rs.getDouble("avg_queue_market"),
                rs.getDouble("avg_queue_limit"),
                rs.getDouble("avg_queue_execution"));
    }

    /**
     * Safe list access — returns 0.0 if index is out of bounds.
     * Prevents IndexOutOfBoundsException if servicePointCount was wrong.
     */
    private double safeGet(List<Double> list, int index) {
        return (list != null && index < list.size()) ? list.get(index) : 0.0;
    }
}