package eds.database;

import eds.database.Records.StatisticsAndMetricsRecord;
import eds.model.StatisticsCollector;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Queries — sole implementation of IQueries.
 *
 * Responsibilities:
 * - Persist simulation run records (statistics_and_metrics table)
 * - Persist trade records linked to a run (trades table)
 * - Retrieve run records and trades for the results view
 *
 * All database access goes through Database.getInstance().getConnection().
 *
 * Integration:
 * - StatisticsCollector.Snapshot → buildRecord() → save() → DB
 * - findById(runId) → StatisticsAndMetricsRecord → PerformanceDescriber
 */
public class Queries {

    // ── Snapshot - Record conversion ──────────────────────────────────────────

    /**
     * Converts a StatisticsCollector.Snapshot and engine config parameters
     * into a StatisticsAndMetricsRecord ready for persistence.
     *
     * This is the single mapping point between the model layer and database layer.
     * Called by Controller after simulation completes.
     */
    public StatisticsAndMetricsRecord buildRecord(
            StatisticsCollector.Snapshot snap,
            String runName,
            long seed,
            double meanValidation,
            double meanMarket,
            double meanLimit,
            double meanExecution,
            double meanArrival,
            double simulationTime) {

        // unpack service point lists by known index order:
        // 0=validation, 1=market matching, 2=limit matching, 3=execution
        List<Double> util = snap.servicePointUtilization();
        List<Double> queue = snap.averageQueueLengthPerServicePoint();

        return new StatisticsAndMetricsRecord(
                0, // id — generated by DB
                LocalDateTime.now().toString(), // runTimestamp
                runName,
                seed,
                meanValidation,
                meanMarket,
                meanLimit,
                meanExecution,
                meanArrival,
                simulationTime,
                (int) snap.totalArrivedOrders(), // totalOrders
                (int) snap.totalTrades(), // totalTrades
                (int) snap.totalExecutedOrders(), // filledOrders
                (int) (snap.totalArrivedOrders() // cancelledOrders — derived
                        - snap.totalExecutedOrders()
                        - snap.remainingOrdersInBook()),
                snap.remainingOrdersInBook(), // remainingOrders
                snap.vwap(),
                snap.averageMidPrice(),
                snap.minPrice(),
                snap.maxPrice(),
                snap.averageSpread(),
                snap.averageWaitingTime(), // avgLatency
                snap.throughput(),
                snap.fillRate(), // decimal 0.0–1.0
                safeGet(util, 0), // utilizationValidation
                safeGet(util, 1), // utilizationMarket
                safeGet(util, 2), // utilizationLimit
                safeGet(util, 3), // utilizationExecution
                safeGet(queue, 0), // avgQueueValidation
                safeGet(queue, 1), // avgQueueMarket
                safeGet(queue, 2), // avgQueueLimit
                safeGet(queue, 3) // avgQueueExecution
        );
    }

    /**
     * Safe list access — returns 0.0 if index is out of bounds.
     * Prevents IndexOutOfBoundsException if servicePointCount was wrong.
     */
    private double safeGet(List<Double> list, int index) {
        return (list != null && index < list.size()) ? list.get(index) : 0.0;
    }
}